export const environment = {
  SUPABASE_KEY:
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdyeWR4cW9haXVmemtuZnFyeWRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTc5NDc4NDYsImV4cCI6MjAzMzUyMzg0Nn0.XtjTcjKwn5--3NNrRKNtlViED9iu_yy_ORz327AHISw',
  SUPABASE_URL: 'https://grydxqoaiufzknfqrydc.supabase.co',
  // SYNCFUSION_KEY:
  //   'Ngo9BigBOggjHTQxAR8/V1NBaF1cXmhPYVJwWmFZfVpgd19DYlZVQ2Y/P1ZhSXxXdkNjUH5bdXZRQWRdV00=',
  SYNCFUSION_KEY:
    'ORg4AjUWIQA/Gnt2UFhhQlJBfV5AQmBIYVp/TGpJfl96cVxMZVVBJAtUQF1hTX5Vd0ZiX31YdHBWQGNa',
  STRIPE_PUBLISHABLE_KEY: ''
};
